name: Show Opt Results

on:
  # workflow_dispatch:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: write
  pull-requests: write

env:
  WORKSPACE:              ${{ github.workspace }}
  LLVM_SRC_DIR:           ${{ github.workspace }}/repos/llvm-project
  TS_SRC_DIR:             ${{ github.workspace }}/repos/llvm-test-suite
  BUILDS_DIR:             ${{ github.workspace }}/build
  BUILD_LLVM_DIR:         ${{ github.workspace }}/build/build-llvm
  BUILD_TS_DIR:           ${{ github.workspace }}/build/build-test-suite
  RESULTS_DIR:            ${{ github.workspace }}/results


jobs:
  configure:
    runs-on: [self-hosted, llvm-ci]
    outputs:
      PR_ID: ${{ steps.extract.outputs.PR_ID }}
      FLAG:  ${{ steps.extract.outputs.FLAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0
        
      - name: Cleanup old builds
        run: |
          if [ -d "${BUILDS_DIR}" ]; then
            rm -rf ${BUILDS_DIR}/*
          else
            mkdir -p ${BUILDS_DIR}
          fi
      
      - name: Update repos
        run: |
          cd ${WORKSPACE}
          sh scripts/fetch-upstream.sh
      
      - name: Extract issue body
        id: extract
        env:
          GH_ISSUE_BODY: ${{ github.event.issue.body }}
        run: sh scripts/extract-issue-body.sh

  without-pr:
    needs: configure
    runs-on: [self-hosted, llvm-ci]
    steps:
      - name: Checkout PR branch without pull commits.
        run: |
          PR_BRANCH=pr-${{ needs.configure.outputs.PR_ID }}-$(date +%s)
          cd ${LLVM_SRC_DIR}

          git fetch origin pull/${{ needs.configure.outputs.PR_ID }}/head:${PR_BRANCH}
          git checkout ${PR_BRANCH}

          pr_commits=$(git rev-list main.. --count)
          git checkout HEAD~${pr_commits}

          cd ${WORKSPACE}
          sh scripts/build-llvm.sh

      - name: Generate Test Suite Asm files
        env:
          FLAG: ${{ needs.configure.outputs.FLAG }}
        run: |
          cd ${WORKSPACE}
          sh scripts/build-test-suite.sh
          sh scripts/copy-asm.sh before

  with-pr:
    needs: [without-pr, configure]
    runs-on: [self-hosted, llvm-ci]
    steps:
      - name: Checkout PR branch with pull commits.
        run: |
          cd ${LLVM_SRC_DIR}
          git switch -

          cd ${WORKSPACE}
          sh scripts/build-llvm.sh

      - name: Generate Test Suite Asm files
        env:
          FLAG: ${{ needs.configure.outputs.FLAG }}
        run: |
          cd ${WORKSPACE}
          sh scripts/build-test-suite.sh
          sh scripts/copy-asm.sh after

  results:
    needs: [with-pr, configure]
    runs-on: [self-hosted, llvm-ci]
    steps:
      - name: Diff PR
        id: pr
        env:
          GH_ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          FLAG: ${{ needs.configure.outputs.FLAG }}
          PR_ID: ${{ needs.configure.outputs.PR_ID }}
        run: |
          cd ${WORKSPACE}
          sh scripts/diff-pr.sh
      
      - name: Create comment
        uses: actions-cool/issue-helper@v3.7.6
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}
            Optimization results can be found:  ${{ steps.pr.outputs.PR_URL }}
